{
 "title": "Siddhi Trigger Statistics",
 "tags": [
  "prometheus",
  "siddhi"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(siddhi_stream_throughput_total,instance)"
   },
   {
    "name": "application",
    "label": "Application",
    "query": "label_values(siddhi_stream_throughput_total{instance=\"$instance\"},app)"
   },
   { "name": "type", "label": "Type", "query": "label_values(type)" },
   { "name": "metrics", "label": "Metrics", "query": "label_values(metrics)" },
   {
    "name": "element",
    "label": "Element",
    "query": "label_values(siddhi_trigger_throughput_total{instance=\"$instance\",app=\"$application\"},element)"
   }
  ]
 },
 "panels": [
  {
   "title": "Trigger Statistics Summary",
   "type": "table",
   "gridPos": { "h": 7, "w": 19, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(siddhi_trigger_throughput_total{instance=~\"$instance\",app=~\"$application\"}) by (app,element)"
    }
   ]
  },
  {
   "title": "Back to Overall Statistics",
   "type": "dashlist",
   "gridPos": { "h": 3, "w": 5, "x": 19, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Trigger Count",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(count(siddhi_trigger_throughput_total{instance=~\"$instance\",app=~\"$application\"}))"
    }
   ]
  },
  {
   "title": "Throughput",
   "type": "graph",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "siddhi_trigger_throughput_total{instance=~\"$instance\",app=~\"$application\"}",
     "legendFormat": "trigger throughput{app=\"{{app}}\", element=\"{{element}}\", instance=\"{{instance}}\" }"
    }
   ]
  }
 ]
}