{
 "title": "Siddhi Server Statistics",
 "tags": [
  "prometheus ",
  "siddhi"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "instance",
    "query": "label_values(jvm_memory_heap_max,instance)"
   },
   {
    "name": "application",
    "label": "Application",
    "query": "label_values(siddhi_stream_throughput_total,app)"
   },
   {
    "name": "element",
    "label": "Element",
    "query": "label_values(siddhi_stream_throughput_total{app=\"$application\"},element)"
   },
   { "name": "type", "label": "Type", "query": "label_values(type)" }
  ]
 },
 "panels": [
  {
   "title": "Servers Up/Down",
   "type": "graph",
   "gridPos": { "h": 6, "w": 19, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "up{instance=~\"$instance\"}",
     "legendFormat": "{{instance}} - {{job}}"
    }
   ]
  },
  {
   "title": "Back to Overall Statistics",
   "type": "dashlist",
   "gridPos": { "h": 3, "w": 5, "x": 19, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Siddhi Apps",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 19, "y": 3 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(count(count by (app) (siddhi_stream_throughput_total{instance=~\"$instance\"})))"
    }
   ]
  },
  {
   "title": "Server Statistics Summary",
   "type": "table",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "sum(siddhi_source_throughput_total{instance=~\"$instance\",type=\"source\",operation!=\"inMemory\"}) by (instance)"
    },
    {
     "expr": "sum(jvm_os_system_load_average{instance=~\"$instance\"}) by (instance)"
    },
    {
     "expr": "sum(jvm_os_cpu_load_system{instance=~\"$instance\"}) by (instance)"
    },
    {
     "expr": "sum(jvm_memory_heap_usage{instance=~\"$instance\"}) by (instance)"
    }
   ]
  },
  {
   "title": "Overall Throughput",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(siddhi_source_throughput_total{instance=~\"$instance\",type=\"source\",operation!=\"inMemory\"})",
     "legendFormat": "overall throughput{instance=\"{{instance}}\" }"
    }
   ]
  },
  {
   "title": "System Load Average",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_os_system_load_average{instance=~\"$instance\"}",
     "legendFormat": "system load average{instance=\"{{instance}}\" }"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "jvm_os_cpu_load_system{instance=~\"$instance\"}",
     "legendFormat": "system cpu usage{instance=\"{{instance}}\" }"
    },
    {
     "expr": "jvm_os_cpu_load_process{instance=~\"$instance\"}",
     "legendFormat": "process cpu usage{instance=\"{{instance}}\" }"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_heap_usage{instance=~\"$instance\"}",
     "legendFormat": "used memory{instance=\"{{instance}}\" }"
    },
    {
     "expr": "jvm_memory_heap_max{instance=~\"$instance\"}",
     "legendFormat": "total memory{instance=\"{{instance}}\" }"
    }
   ]
  },
  {
   "title": "JVM Physical Memory",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 51 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "jvm_os_physical_memory_total_size{instance=~\"$instance\"}",
     "legendFormat": "physical memory total{instance=\"{{instance}}\" }"
    },
    {
     "expr": "jvm_os_physical_memory_free_size{instance=~\"$instance\"}",
     "legendFormat": "physical memory free{instance=\"{{instance}}\" }"
    }
   ]
  },
  {
   "title": "JVM Threads ",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 61 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_threads_count{instance=~\"$instance\"}",
     "legendFormat": "threads count{instance=\"{{instance}}\" }"
    },
    {
     "expr": "jvm_threads_daemon_count{instance=~\"$instance\"}",
     "legendFormat": "daemon threads count{instance=\"{{instance}}\" }"
    }
   ]
  },
  {
   "title": "JVM Class Load",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 71 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_class_loading_unloaded_total{instance=~\"$instance\"}",
     "legendFormat": "unloaded total{instance=\"{{instance}}\" }"
    },
    {
     "expr": "jvm_class_loading_loaded_current{instance=~\"$instance\"}",
     "legendFormat": "loaded current{instance=\"{{instance}}\" }"
    },
    {
     "expr": "jvm_class_loading_loaded_total{instance=~\"$instance\"}",
     "legendFormat": "loaded total{instance=\"{{instance}}\" }"
    }
   ]
  },
  {
   "title": "JVM Swap Space",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 81 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_os_swap_space_total_size{instance=~\"$instance\"}",
     "legendFormat": "total swap size{instance=\"{{instance}}\" }"
    },
    {
     "expr": "jvm_os_swap_space_free_size{instance=~\"$instance\"}",
     "legendFormat": "free swap size{instance=\"{{instance}}\" }"
    }
   ]
  }
 ]
}