{
 "title": "Siddhi Overall Statistics",
 "tags": [
  "prometheus",
  "siddhi"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(siddhi_stream_throughput_total,instance)"
   },
   {
    "name": "application",
    "label": "Application",
    "query": "label_values(siddhi_stream_throughput_total,app)"
   },
   { "name": "type", "label": "Type", "query": "label_values(type)" },
   { "name": "metrics", "label": "Metrics", "query": "label_values(metrics)" },
   { "name": "element", "label": "Element", "query": "label_values(element)" },
   { "name": "quantile", "label": "Quantile", "query": "label_values(quantile)" },
   { "name": "operation", "label": "Operation", "query": "label_values(operation)" },
   { "name": "job", "label": "Job", "query": "label_values(job)" }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 1.25, "w": 24, "x": 0, "y": 0 },
   "content": "<b><h5> Server Statistics</h5></b>\n\n\n\n"
  },
  {
   "title": "Servers Up/Down",
   "type": "graph",
   "gridPos": { "h": 6, "w": 19, "x": 0, "y": 1.25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "up{instance=~\"$instance\"}",
     "legendFormat": "{{instance}} - {{job}}"
    }
   ]
  },
  {
   "title": "Detailed View",
   "type": "dashlist",
   "gridPos": { "h": 3, "w": 5, "x": 19, "y": 1.25 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Siddhi Apps",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 19, "y": 4.25 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(count(count by (app,instance) (siddhi_stream_throughput_total{instance=~\"$instance\",app=~\"$application\"})))"
    }
   ]
  },
  {
   "title": "Server Statistics Summary",
   "type": "table",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 7.25 },
   "targets": [
    {
     "expr": "sum(siddhi_source_throughput_total{instance=~\"$instance\",type=\"source\",operation!=\"inMemory\"}) by (instance)"
    },
    {
     "expr": "sum(jvm_os_system_load_average{instance=~\"$instance\"}) by (instance)"
    },
    {
     "expr": "sum(jvm_os_cpu_load_system{instance=~\"$instance\"}) by (insance)"
    },
    {
     "expr": "sum(jvm_memory_heap_usage{instance=~\"$instance\"}) by (instance)"
    }
   ]
  },
  {
   "title": "Overall Throughput",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 12.25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(siddhi_source_throughput_total{type=\"source\",operation!=\"inMemory\",instance=~\"$instance\"})",
     "legendFormat": "overall throughput{instance=\"{{instance}}\" }"
    }
   ]
  },
  {
   "title": "System Load Average",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 12.25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_os_system_load_average{instance=~\"$instance\"}",
     "legendFormat": "system load average{instance=\"{{instance}}\" }"
    }
   ]
  },
  {
   "title": "Process CPU Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 18.25 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "jvm_os_cpu_load_process{instance=~\"$instance\"}",
     "legendFormat": "cpu process load{instance=\"{{instance}}\" }"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 18.25 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_heap_usage{instance=~\"$instance\"}",
     "legendFormat": "memory heap usage{instance=\"{{instance}}\" }"
    }
   ]
  },
  {
   "title": "Thread Count",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 24.25 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(jvm_threads_count{instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Threads Blocked",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 24.25 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(jvm_threads_blocked_count{instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Memory Heap Used",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 24.25 },
   "format": "decbytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(jvm_memory_heap_used{instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "File Descriptors open",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 24.25 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(jvm_os_file_descriptor_open_count{instance=~\"$instance\"})"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 1.25, "w": 24, "x": 0, "y": 27.25 },
   "content": "<b><h5> Stream Statistics</h5></b>\n\n\n\n"
  },
  {
   "title": "Stream Statistics Summary",
   "type": "table",
   "gridPos": { "h": 7, "w": 19, "x": 0, "y": 28.5 },
   "targets": [
    {
     "expr": "sum(siddhi_stream_throughput_total{instance=~\"$instance\",app=~\"$application\"}) by (app,element)"
    }
   ]
  },
  {
   "title": "Detailed View",
   "type": "dashlist",
   "gridPos": { "h": 3, "w": 5, "x": 19, "y": 28.5 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Stream Count",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 31.5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(count(siddhi_stream_throughput_total{instance=~\"$instance\",app=~\"$application\"}))"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 1.25, "w": 24, "x": 0, "y": 35.5 },
   "content": "<b><h5> Query Statistics</h5></b>\n\n\n\n"
  },
  {
   "title": "Query Statistics Summary",
   "type": "table",
   "gridPos": { "h": 7, "w": 19, "x": 0, "y": 36.75 },
   "targets": [
    {
     "expr": "sum(siddhi_query_memory{instance=~\"$instance\",app=~\"$application\"}) by (app,element)"
    },
    {
     "expr": "sum(siddhi_query_latency{instance=~\"$instance\",app=~\"$application\"}) by (app,element)"
    }
   ]
  },
  {
   "title": "Detailed View",
   "type": "dashlist",
   "gridPos": { "h": 3, "w": 5, "x": 19, "y": 36.75 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Query Count",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 39.75 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(count(siddhi_query_memory{instance=~\"$instance\",app=~\"$application\"}))"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 1.25, "w": 24, "x": 0, "y": 43.75 },
   "content": "<b><h5> Source & Source Mapper Statistics</h5></b>\n\n\n\n"
  },
  {
   "title": "Source Mapper Statistics Summary",
   "type": "table",
   "gridPos": { "h": 7, "w": 20, "x": 0, "y": 45 },
   "targets": [
    {
     "expr": "sum(siddhi_sourcemapper_latency{instance=~\"$instance\",app=~\"$application\"}) by (app,element,operation,operationType)"
    },
    {
     "expr": "sum(siddhi_source_throughput_total{instance=~\"$instance\",app=~\"$application\"}) by (app,element,operation)"
    }
   ]
  },
  {
   "title": "Detailed View",
   "type": "dashlist",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 45 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Source Count",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 48 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(count(siddhi_source_throughput_total{instance=~\"$instance\",app=~\"$application\"}))"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 1.25, "w": 24, "x": 0, "y": 52 },
   "content": "<b><h5> Sink Statistics</h5></b>\n\n\n\n"
  },
  {
   "title": "Sink Mapper Statistics Summary",
   "type": "table",
   "gridPos": { "h": 7, "w": 20, "x": 0, "y": 53.25 },
   "targets": [
    {
     "expr": "sum(siddhi_sinkmapper_latency{instance=~\"$instance\",app=~\"$application\"}) by (app,element,operation,operationType)"
    },
    {
     "expr": "sum(siddhi_sink_throughput_total{instance=~\"$instance\",app=~\"$application\"}) by (app,element)"
    }
   ]
  },
  {
   "title": "Detailed View",
   "type": "dashlist",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 53.25 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Sink Count",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 56.25 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(count(siddhi_sink_throughput_total{instance=~\"$instance\",app=~\"$application\"}))"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 1.25, "w": 24, "x": 0, "y": 60.25 },
   "content": "<b><h5> Table Statistics</h5></b>\n\n\n\n"
  },
  {
   "title": "Table Statistics Summary",
   "type": "table",
   "gridPos": { "h": 7, "w": 19, "x": 0, "y": 61.5 },
   "targets": [
    {
     "expr": "sum(siddhi_table_latency{instance=~\"$instance\",app=~\"$application\",element!~\".*SECONDS|.*MINUTES|.*HOURS|.*DAYS|.*MONTHS|.*YEARS\"}) by (app,element,operation)"
    },
    {
     "expr": "sum(siddhi_table_throughput_total{instance=~\"$instance\",app=~\"$application\",element!~\".*SECONDS|.*MINUTES|.*HOURS|.*DAYS|.*MONTHS|.*YEARS\"}) by (app,element,operation)"
    }
   ]
  },
  {
   "title": "Detailed View",
   "type": "dashlist",
   "gridPos": { "h": 3, "w": 5, "x": 19, "y": 61.5 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Table Count",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 64.5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(count(count by (element) (siddhi_table_latency{instance=~\"$instance\",app=~\"$application\",element!~\".*SECONDS|.*MINUTES|.*HOURS|.*DAYS|.*MONTHS|.*YEARS\"})))"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 1.25, "w": 24, "x": 0, "y": 68.5 },
   "content": "<b><h5> Window Statistics</h5></b>\n\n\n\n"
  },
  {
   "title": "Window Statistics Summary",
   "type": "table",
   "gridPos": { "h": 7, "w": 19, "x": 0, "y": 69.75 },
   "targets": [
    {
     "expr": "sum(siddhi_window_memory{instance=~\"$instance\",app=~\"$application\"}) by (app,element)"
    },
    {
     "expr": "sum(siddhi_window_latency{instance=~\"$instance\",app=~\"$application\",quantile=\"0.95\"}) by (app,element)"
    },
    {
     "expr": "sum(siddhi_window_throughput_total{instance=~\"$instance\",app=~\"$application\"}) by (app,element)"
    }
   ]
  },
  {
   "title": "Detailed View",
   "type": "dashlist",
   "gridPos": { "h": 3, "w": 5, "x": 19, "y": 69.75 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Window Count",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 72.75 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(count(count by (element) (siddhi_window_latency{instance=~\"$instance\",app=~\"$application\"})))"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 1.25, "w": 24, "x": 0, "y": 76.75 },
   "content": "<b><h5> Aggregation Statistics</h5></b>\n\n\n\n"
  },
  {
   "title": "Aggregation Statistics Summary",
   "type": "table",
   "gridPos": { "h": 7, "w": 19, "x": 0, "y": 78 },
   "targets": [
    {
     "expr": "sum(siddhi_aggregation_memory{instance=~\"$instance\",app=~\"$application\"}) by (app,element)"
    },
    {
     "expr": "sum(siddhi_aggregation_latency{instance=~\"$instance\",app=~\"$application\"}) by (app,element)"
    },
    {
     "expr": "sum(siddhi_aggregation_throughput_total{instance=~\"$instance\",app=~\"$application\"}) by (app,element)"
    }
   ]
  },
  {
   "title": "Detailed View",
   "type": "dashlist",
   "gridPos": { "h": 3, "w": 5, "x": 19, "y": 78 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Aggregation Count",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 81 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(count(count by (element) (siddhi_aggregation_throughput_total{instance=~\"$instance\",app=~\"$application\"})))"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 1.25, "w": 24, "x": 0, "y": 85 },
   "content": "<b><h5> Trigger Statistics</h5></b>\n\n\n\n"
  },
  {
   "title": "Trigger Statistics Summary",
   "type": "table",
   "gridPos": { "h": 7, "w": 19, "x": 0, "y": 86.25 },
   "targets": [
    {
     "expr": "sum(siddhi_trigger_throughput_total{instance=~\"$instance\",app=~\"$application\"}) by (app,element)"
    }
   ]
  },
  {
   "title": "Detailed View",
   "type": "dashlist",
   "gridPos": { "h": 3, "w": 5, "x": 19, "y": 86.25 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Trigger Count",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 89.25 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(count(siddhi_trigger_throughput_total{instance=~\"$instance\",app=~\"$application\"}))"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 1.25, "w": 24, "x": 0, "y": 93.25 },
   "content": "<b><h5> On-Demand Query Statistics</h5></b>\n\n\n\n"
  },
  {
   "title": "On-Demand Query Statistics Summary",
   "type": "table",
   "gridPos": { "h": 7, "w": 19, "x": 0, "y": 94.5 },
   "targets": [
    {
     "expr": "sum(siddhi_ondemandquery_latency{instance=~\"$instance\",app=~\"$application\"}) by (app)"
    }
   ]
  },
  {
   "title": "Detailed View",
   "type": "dashlist",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 94.5 },
   "targets": [
    {}
   ]
  }
 ]
}